
# These tasks install the C++ program that actually drives the Neje engraver.

- name: Empty the github clone directory
  file: path="{{ githubCloneDirectory }}" state=absent
  
- name: Creates github clone directory
  file: path="{{ githubCloneDirectory }}" state=directory

- git:
    repo: 'https://github.com/onebeartoe/EzGraver.git'
    version: unix_cli_fixes_clean
    dest: "{{ githubCloneDirectory }}"

- name: Ensure the desired QT version has been installed.
  shell: qmake -qt=qt5 -v
  args:
    chdir: "{{ githubCloneDirectory }}"

- name: Build EzGraver - A.
  shell: qmake -qt=qt5 -config release EzGraver.pro
  args:
    chdir: "{{ githubCloneDirectory }}"

- name: Build EzGraver - B.
  shell: make
  args:
    chdir: "{{ githubCloneDirectory }}"

- name: Install EzGraver binaries
  shell: make install
  args:
    chdir: "{{ githubCloneDirectory }}"
